Update ITS_delay.py To resolve NumPy 2.0 compatibility....
err: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 import mcvqoe.base

File D:\PSCR_projects\QoE_ASL_pyvenvs\StockMCVQoE\lib\site-packages\mcvqoe\base\__init__.py:5
      3 from .write_log import pre, post
      4 from .audio_channels import *
----> 5 from .fsf import *
      6 from .naming import get_meas_basename, get_access_clip_info, get_meas_date_str, match_name
      7 from .measurement import Measure

File D:\PSCR_projects\QoE_ASL_pyvenvs\StockMCVQoE\lib\site-packages\mcvqoe\base\fsf.py:2
      1 import math
----> 2 import mcvqoe.delay
      3 import warnings
      5 import numpy as np

File D:\PSCR_projects\QoE_ASL_pyvenvs\StockMCVQoE\lib\site-packages\mcvqoe\delay\__init__.py:2
----> 2 from .ITS_delay import ITS_delay_est
      3 from .sliding_delay import sliding_delay_estimates

File D:\PSCR_projects\QoE_ASL_pyvenvs\StockMCVQoE\lib\site-packages\mcvqoe\delay\ITS_delay.py:8
      4 import scipy.signal as sig
      5 from numpy.fft import fft, ifft
----> 8 def ITS_delay_est(x_speech, y_speech, mode, fs=8000, dlyBounds=[np.NINF, np.inf], min_corr=0):
      9     """
     10     Estimate the delay history for speech wave forms.
     11 
   (...)
     90     array([0, 0])
     91     """
     92     # ----------------------------Parse Arguments--------------------------------

File D:\PSCR_projects\QoE_ASL_pyvenvs\StockMCVQoE\lib\site-packages\numpy\__init__.py:413, in __getattr__(attr)
    410     raise AttributeError(__former_attrs__[attr], name=None)
    412 if attr in __expired_attributes__:
--> 413     raise AttributeError(
    414         f"`np.{attr}` was removed in the NumPy 2.0 release. "
    415         f"{__expired_attributes__[attr]}",
    416         name=None
    417     )
    419 if attr == "chararray":
    420     warnings.warn(
    421         "`np.chararray` is deprecated and will be removed from "
    422         "the main namespace in the future. Use an array with a string "
    423         "or bytes dtype instead.", DeprecationWarning, stacklevel=2)

AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.